
[db.migrations]
schema_paths = [
  "schemas",
]

# Temporary development setting. Re-enable after custom SMTP is configured.
[auth.email]
enable_confirmations = false

[functions.create-checkout-session]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.wikipedia-refresher]
verify_jwt = true
