CREATE TABLE "public"."content" (
  "content_id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "category_id"         bigint,
  "genre_id"            bigint,
  "title"               character varying(255)   NOT NULL,
  "synopsis"            text,
  "release_year"        integer,
  "runtime"             integer,
  "age_rating"          character varying(20),
  "thumbnail"           text,
  "video_file"          text,
  "subtitle"            text,
  "total_streams_count" bigint                   NOT NULL DEFAULT 0,
  "availability_status" character varying(50),
  "tmdb_id"             bigint,
  "popularity_rank"     integer,
  "catalog_source"      character varying(20)    NOT NULL DEFAULT 'manual'::character varying,
  "synced_at"           timestamp with time zone,
  CONSTRAINT "content_catalog_source_check" CHECK (((catalog_source)::text = ANY ((ARRAY['manual'::character varying, 'tmdb'::character varying])::text[]))),
  CONSTRAINT "content_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.category(category_id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT "content_pkey" PRIMARY KEY (content_id),
  CONSTRAINT "content_popularity_rank_check" CHECK (((popularity_rank IS NULL) OR ((popularity_rank >= 1) AND (popularity_rank <= 50)))),
  CONSTRAINT "content_release_year_check" CHECK ((release_year >= 1888)),
  CONSTRAINT "content_runtime_check" CHECK ((runtime > 0)),
  CONSTRAINT "content_tmdb_reference_unique" UNIQUE (category_id, tmdb_id),
  CONSTRAINT "content_total_streams_count_check" CHECK ((total_streams_count >= 0)),
  CONSTRAINT "content_genre_id_fkey" FOREIGN KEY (genre_id) REFERENCES public.genre(genre_id) ON UPDATE CASCADE ON DELETE SET NULL
);

ALTER TABLE "public"."content"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX content_category_id_idx ON public.content USING btree (category_id);

CREATE INDEX content_category_rank_idx ON public.content USING btree (category_id, popularity_rank)
  WHERE ((availability_status)::text = 'available'::text);

CREATE INDEX content_genre_id_idx ON public.content USING btree (genre_id);

CREATE POLICY "content_manager_delete_content" ON "public"."content"
  FOR DELETE
  TO "authenticated"
  USING (public.is_any_admin());

CREATE POLICY "content_manager_insert_content" ON "public"."content"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (public.is_any_admin());

CREATE POLICY "content_manager_update_content" ON "public"."content"
  FOR UPDATE
  TO "authenticated"
  USING (public.is_any_admin())
  WITH CHECK (public.is_any_admin());

CREATE POLICY "user_can_view_available_content" ON "public"."content"
  FOR SELECT
  TO PUBLIC
  USING (((availability_status)::text = 'available'::text));

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."content" TO "anon", "authenticated", "postgres", "service_role";

COMMENT ON COLUMN "public"."content"."catalog_source" IS 'Origin of the catalog record. TMDB imports use tmdb.';

COMMENT ON COLUMN "public"."content"."popularity_rank" IS 'Current rank within the imported top-50 movie or TV catalog.';

COMMENT ON COLUMN "public"."content"."tmdb_id" IS 'Permanent external identifier supplied by The Movie Database.';
