CREATE TABLE "public"."member_profile" (
  "member_profile_id" bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"           uuid                     NOT NULL,
  "is_active"         boolean                  NOT NULL DEFAULT true,
  "profile_name"      character varying(50)    NOT NULL,
  "avatar_image"      text,
  "is_kids"           boolean                  NOT NULL DEFAULT false,
  "pin_hash"          text,
  "display_order"     smallint                 NOT NULL DEFAULT 1,
  "created_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"        timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "member_profile_display_order_positive" CHECK ((display_order > 0)),
  CONSTRAINT "member_profile_name_not_blank" CHECK ((btrim((profile_name)::text) <> ''::text)),
  CONSTRAINT "member_profile_pin_hash_not_blank" CHECK (((pin_hash IS NULL) OR (btrim(pin_hash) <> ''::text))),
  CONSTRAINT "member_profile_pkey" PRIMARY KEY (member_profile_id),
  CONSTRAINT "member_profile_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."user"(user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE "public"."member_profile"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_member_profile_user_id ON public.member_profile USING btree (user_id);

CREATE UNIQUE INDEX member_profile_active_name_unique ON public.member_profile USING btree (user_id, lower(btrim((profile_name)::text)))
  WHERE is_active;

CREATE UNIQUE INDEX member_profile_active_order_unique ON public.member_profile USING btree (user_id, display_order)
  WHERE is_active;

CREATE TRIGGER set_member_profile_updated_at
  BEFORE UPDATE ON public.member_profile
  FOR EACH ROW
  EXECUTE FUNCTION public.set_member_profile_updated_at();

CREATE POLICY "user_manager_full_member_profile_control" ON "public"."member_profile"
  FOR ALL
  TO PUBLIC
  USING ((public.is_admin_role('userManager'::character varying) OR public.is_master_admin()))
  WITH CHECK ((public.is_admin_role('userManager'::character varying) OR public.is_master_admin()));

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."member_profile" TO "anon", "authenticated", "postgres", "service_role";

COMMENT ON COLUMN "public"."member_profile"."avatar_image" IS 'Avatar asset key or image URL selected for this viewing profile.';

COMMENT ON COLUMN "public"."member_profile"."display_order" IS 'One-based position of the profile in the account profile picker.';

COMMENT ON COLUMN "public"."member_profile"."is_kids" IS 'Whether the viewing profile should receive child-appropriate content.';

COMMENT ON COLUMN "public"."member_profile"."pin_hash" IS 'Optional secure hash of a profile PIN; never store the raw PIN.';

COMMENT ON COLUMN "public"."member_profile"."profile_name" IS 'Viewer-facing profile name within the subscriber account.';
