CREATE TABLE "public"."platform_feedback" (
  "feedback_id"     bigint                      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"         uuid                        NOT NULL,
  "feedback_type"   character varying(50),
  "subject"         character varying(255),
  "description"     text,
  "screenshot"      text,
  "submission_date" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "platform_feedback_pkey" PRIMARY KEY (feedback_id),
  CONSTRAINT "platform_feedback_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."user"(user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE "public"."platform_feedback"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX platform_feedback_user_id_idx ON public.platform_feedback USING btree (user_id);

CREATE POLICY "admin_can_delete_feedback" ON "public"."platform_feedback"
  FOR DELETE
  TO "authenticated"
  USING (public.is_any_admin());

CREATE POLICY "allow_select_feedback" ON "public"."platform_feedback"
  FOR SELECT
  TO "authenticated"
  USING ((public.is_any_admin() OR (user_id IN ( SELECT u.user_id
   FROM public."user" u
  WHERE (u.auth_user_id = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "user_can_insert_own_feedback" ON "public"."platform_feedback"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((user_id = ( SELECT auth.uid() AS uid)));

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."platform_feedback" TO "anon", "authenticated", "postgres", "service_role";
