CREATE TABLE "public"."soundtrack" (
  "soundtrack_id" bigint                 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "content_id"    bigint                 NOT NULL,
  "song_title"    character varying(255) NOT NULL,
  "artist"        character varying(255),
  "stream_link"   text,
  "track_title"   text,
  "external_url"  text,
  CONSTRAINT "soundtrack_content_id_fkey" FOREIGN KEY (content_id) REFERENCES public.content(content_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "soundtrack_pkey" PRIMARY KEY (soundtrack_id)
);

ALTER TABLE "public"."soundtrack"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_soundtrack_content_id ON public.soundtrack USING btree (content_id);

CREATE POLICY "content_manager_delete_soundtrack" ON "public"."soundtrack"
  FOR DELETE
  TO "authenticated"
  USING (public.is_any_admin());

CREATE POLICY "content_manager_insert_soundtrack" ON "public"."soundtrack"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (public.is_any_admin());

CREATE POLICY "content_manager_update_soundtrack" ON "public"."soundtrack"
  FOR UPDATE
  TO "authenticated"
  USING (public.is_any_admin())
  WITH CHECK (public.is_any_admin());

CREATE POLICY "user_can_view_soundtrack" ON "public"."soundtrack"
  FOR SELECT
  TO PUBLIC
  USING (true);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."soundtrack" TO "anon", "authenticated", "postgres", "service_role";
