CREATE TABLE "public"."test" (
  "id"         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" text   NOT NULL,
  CONSTRAINT "test_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."test"
  ENABLE ROW LEVEL SECURITY;

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."test" TO "anon", "authenticated", "postgres", "service_role";

COMMENT ON COLUMN "public"."test"."created_at" IS '[SENSITIVE]';
