-- StreamFlix admin integration layer.
-- This migration is intentionally additive: existing application rows and
-- legacy columns are preserved while stable IDs, workflow fields, and missing
-- admin domains are introduced.

create or replace function public.is_master_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.admin
    where auth_user_id = (select auth.uid())
      and lower(replace(role, ' ', '')) = 'masteradmin'
  ) or exists (
    select 1
    from public."user"
    where auth_user_id = (select auth.uid())
      and lower(replace(user_role, ' ', '')) = 'masteradmin'
  );
$$;

create or replace function public.is_admin_role(required_role varchar)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.is_master_admin() or exists (
    select 1
    from public.admin
    where auth_user_id = (select auth.uid())
      and lower(replace(role, ' ', '')) = lower(replace(required_role, ' ', ''))
  );
$$;

create or replace function public.is_any_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.is_master_admin() or exists (
    select 1 from public.admin where auth_user_id = (select auth.uid())
  );
$$;

create or replace function public.get_admin_role()
returns varchar
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select case
    when public.is_master_admin() then 'masterAdmin'::varchar
    else (
      select role from public.admin
      where auth_user_id = (select auth.uid())
      limit 1
    )
  end;
$$;

grant execute on function public.is_master_admin() to authenticated;
grant execute on function public.is_admin_role(varchar) to authenticated;
grant execute on function public.is_any_admin() to authenticated;
grant execute on function public.get_admin_role() to authenticated;

alter table public.admin
  add column if not exists status varchar(30) not null default 'Active',
  add column if not exists last_login timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public."user"
  add column if not exists account_status varchar(30) not null default 'Active',
  add column if not exists joined_at timestamptz not null default now();

alter table public.platform_feedback
  add column if not exists status varchar(30) not null default 'Open',
  add column if not exists updated_at timestamptz not null default now();

alter table public.soundtrack
  add column if not exists lyrics text,
  add column if not exists timestamp_label varchar(30);

alter table public.previous_film_refresher
  add column if not exists refresher_id bigint generated by default as identity,
  add column if not exists availability_status varchar(30) not null default 'available',
  add column if not exists updated_at timestamptz not null default now();

alter table public.reaction
  add column if not exists reaction_id bigint generated by default as identity,
  add column if not exists created_at timestamptz not null default now();

alter table public.content_comment
  add column if not exists comment_id bigint generated by default as identity,
  add column if not exists status varchar(30) not null default 'Active';

alter table public.watch_history
  add column if not exists watch_history_id bigint generated by default as identity;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'previous_film_refresher_pkey') then
    alter table public.previous_film_refresher add constraint previous_film_refresher_pkey primary key (refresher_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'reaction_pkey') then
    alter table public.reaction add constraint reaction_pkey primary key (reaction_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'content_comment_pkey') then
    alter table public.content_comment add constraint content_comment_pkey primary key (comment_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'watch_history_pkey') then
    alter table public.watch_history add constraint watch_history_pkey primary key (watch_history_id);
  end if;
end;
$$;

create table if not exists public.content_genre (
  content_id bigint not null references public.content(content_id) on update cascade on delete cascade,
  genre_id bigint not null references public.genre(genre_id) on update cascade on delete cascade,
  primary key (content_id, genre_id)
);

insert into public.content_genre (content_id, genre_id)
select content_id, genre_id from public.content where genre_id is not null
on conflict do nothing;

create table if not exists public.content_review (
  review_id bigint generated by default as identity primary key,
  content_id bigint not null references public.content(content_id) on update cascade on delete cascade,
  user_id uuid not null references public."user"(user_id) on update cascade on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  review_text text not null,
  status varchar(30) not null default 'Active',
  created_at timestamptz not null default now()
);

create table if not exists public.community_post (
  post_id bigint generated by default as identity primary key,
  user_id uuid not null references public."user"(user_id) on update cascade on delete cascade,
  title varchar(255) not null,
  body text not null,
  status varchar(30) not null default 'Active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.community_comment (
  community_comment_id bigint generated by default as identity primary key,
  post_id bigint not null references public.community_post(post_id) on update cascade on delete cascade,
  user_id uuid not null references public."user"(user_id) on update cascade on delete cascade,
  body text not null,
  status varchar(30) not null default 'Active',
  created_at timestamptz not null default now()
);

create table if not exists public.user_subscription (
  user_subscription_id bigint generated by default as identity primary key,
  user_id uuid not null references public."user"(user_id) on update cascade on delete cascade,
  subscription_id bigint not null references public.subscription(subscription_id) on update cascade on delete restrict,
  started_at timestamptz not null default now(),
  ends_at timestamptz,
  status varchar(30) not null default 'Active',
  created_at timestamptz not null default now()
);

create table if not exists public.payment_transaction (
  payment_id bigint generated by default as identity primary key,
  user_id uuid not null references public."user"(user_id) on update cascade on delete cascade,
  user_subscription_id bigint references public.user_subscription(user_subscription_id) on update cascade on delete set null,
  amount numeric(10, 2) not null check (amount >= 0),
  payment_method varchar(50),
  reference_number varchar(100),
  status varchar(30) not null default 'Pending',
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.system_log (
  system_log_id bigint generated by default as identity primary key,
  event_type varchar(100) not null,
  severity varchar(30) not null default 'Info',
  status varchar(30) not null default 'Success',
  message text not null,
  actor_auth_user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.backup_job (
  backup_job_id bigint generated by default as identity primary key,
  backup_type varchar(50) not null,
  description text,
  status varchar(30) not null default 'Pending',
  storage_path text,
  size_bytes bigint,
  started_at timestamptz,
  completed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.content_genre enable row level security;
alter table public.content_review enable row level security;
alter table public.community_post enable row level security;
alter table public.community_comment enable row level security;
alter table public.user_subscription enable row level security;
alter table public.payment_transaction enable row level security;
alter table public.system_log enable row level security;
alter table public.backup_job enable row level security;

create policy content_genre_read on public.content_genre for select using (true);
create policy content_genre_admin_write on public.content_genre for all to authenticated using (public.is_admin_role('contentManager')) with check (public.is_admin_role('contentManager'));

create policy content_review_read on public.content_review for select using (status = 'Active' or public.is_admin_role('commentManager'));
create policy content_review_owner_insert on public.content_review for insert to authenticated with check (user_id in (select user_id from public."user" where auth_user_id = (select auth.uid())));
create policy content_review_admin_update on public.content_review for update to authenticated using (public.is_admin_role('commentManager')) with check (public.is_admin_role('commentManager'));
create policy content_review_admin_delete on public.content_review for delete to authenticated using (public.is_admin_role('commentManager'));

create policy community_post_read on public.community_post for select using (status = 'Active' or public.is_admin_role('commentManager'));
create policy community_post_owner_insert on public.community_post for insert to authenticated with check (user_id in (select user_id from public."user" where auth_user_id = (select auth.uid())));
create policy community_post_admin_update on public.community_post for update to authenticated using (public.is_admin_role('commentManager')) with check (public.is_admin_role('commentManager'));
create policy community_post_admin_delete on public.community_post for delete to authenticated using (public.is_admin_role('commentManager'));

create policy community_comment_read on public.community_comment for select using (status = 'Active' or public.is_admin_role('commentManager'));
create policy community_comment_owner_insert on public.community_comment for insert to authenticated with check (user_id in (select user_id from public."user" where auth_user_id = (select auth.uid())));
create policy community_comment_admin_update on public.community_comment for update to authenticated using (public.is_admin_role('commentManager')) with check (public.is_admin_role('commentManager'));
create policy community_comment_admin_delete on public.community_comment for delete to authenticated using (public.is_admin_role('commentManager'));

create policy user_subscription_admin_all on public.user_subscription for all to authenticated using (public.is_admin_role('userManager')) with check (public.is_admin_role('userManager'));
create policy user_subscription_owner_read on public.user_subscription for select to authenticated using (user_id in (select user_id from public."user" where auth_user_id = (select auth.uid())));
create policy payment_admin_all on public.payment_transaction for all to authenticated using (public.is_admin_role('userManager')) with check (public.is_admin_role('userManager'));
create policy payment_owner_read on public.payment_transaction for select to authenticated using (user_id in (select user_id from public."user" where auth_user_id = (select auth.uid())));

create policy system_log_admin_read on public.system_log for select to authenticated using (public.is_admin_role('systemManager'));
create policy system_log_admin_insert on public.system_log for insert to authenticated with check (public.is_admin_role('systemManager'));
create policy backup_job_admin_all on public.backup_job for all to authenticated using (public.is_admin_role('systemManager')) with check (public.is_admin_role('systemManager'));

create policy master_admin_manage_admins on public.admin for all to authenticated using (public.is_master_admin()) with check (public.is_master_admin());
create policy feedback_manager_update_feedback on public.platform_feedback for update to authenticated using (public.is_admin_role('feedbackManager')) with check (public.is_admin_role('feedbackManager'));

grant select, insert, update, delete on public.content_genre, public.content_review,
  public.community_post, public.community_comment, public.user_subscription,
  public.payment_transaction, public.system_log, public.backup_job to authenticated;
grant usage, select on all sequences in schema public to authenticated;
